### ISSUE TITLE
Test for adding a new version to an existing packaged app

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#129]
## Precondition:
a) This test assumes that a packaged app already exists with at least one valid version.
b) There is a new version of the packaged app to upload.

## Steps for the test:
1. Go to the versions page for the packaged app.
2. Click on the "Select a file" button under Upload a New Version section.
3. Upload the new version of the packaged app

## Expected result:
a) The new version passes validation and the submission is successful. Upon submission complete, developer navigates to the Reviewer Notes/Release notes page.
b) The app status does not change. If it was "awaiting review" it continues to be in that state. Same for public apps.
c) If the app was awaiting review, the previous version of the packaged app is moved to "Disabled by mozilla"
d) If the app is public, then the newly added version has "awaiting review" status whereas  the previous version remains in "public" status.

**Comment by AndreiH** [comment]
PR was merged, we have a test for adding a new version. Closing
