### ISSUE TITLE
Test signing in to marketplace using Firefox Accounts as a new user

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#534]
## Steps to test
1. Load marketplace-dev on your  desktop firefox browser
2. Click on the Sign in button
3. In the FxA pop-up, click on the 'Create an account' link
4.  Enter email, password and year of birth 
5. Confirm  by clicking on the email sent to your account

## expected behavior:
Log in is successful

**Comment by bobsilverberg** [comment]
@krupa Do we still need this exact test? We have tests in which we log in to Marketplace using a temporary Firefox Account that we pre-create for the test. It seems like these steps are more a test of FxA then of Marketplace. Do you think our existing coverage is ok, or do we still need to create a new FxA while trying to log in to Marketplace?

**Comment by bobsilverberg** [comment]
@krupa There is a question above awaiting an answer from you.

**Comment by stephendonner** [comment]
Closing per https://github.com/mozilla/marketplace-tests/issues/760
