### ISSUE TITLE
Investigate and find another solution for "self._reviews_setup()" in test_that_checks_the_addition_of_a_review

### ISSUE THREAD

**Issue by AndreiH** [mozilla/marketplace-tests#563]
As discussed in https://github.com/mozilla/marketplace-tests/pull/554 there is no reason why we should add a review and then delete it here: https://github.com/mozilla/marketplace-tests/blob/master/tests/desktop/consumer_pages/test_reviews.py#L33
Investigate and look for another method for this.

**Comment by stephendonner** [comment]
Closing due to https://github.com/mozilla/marketplace-tests/issues/760
