### ISSUE TITLE
Review is added incorrect on Saucelabs

### ISSUE THREAD

**Issue by AndreiH** [mozilla/marketplace-tests#568]
http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.dev.mobile.saucelabs/1492/HTML_Report/
AssertionError: AutomaticReviewSeleniumTests141299 is not found in AutomaticReviewSeleniumTests1414155299.
See the run here: http://saucelabs.com/jobs/2e62bc062f6b417594b3dd17bd905efa
This reminds me of issue that we had a while back: https://github.com/mozilla/marketplace-tests/pull/223 on sauce

I cannot reproduce this on my local Android emulator or Manually.

**Comment by AndreiH** [comment]
This started intermittently passing on dev.

**Comment by davehunt** [comment]
I'm unable to access any of the original links, which makes this almost impossible to investigate now. We should try removing the xfail to see if it's still an issue (or look at the recent results history). I'm not sure I understand how a Chrome issue could cause this, as I believe the test is using the default browser on Android. Until we have more information, I'm going to close this.
