### ISSUE TITLE
Investigate/fix test_that_application_page_contains_proper_objects (support email text/link)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/marketplace-tests#601]
http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.PROD/1882/console
http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.PROD.saucelabs/1671/
http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.PROD.saucelabs.sanity_tests.andreih/91/

Recent marketplace.prod.* failures (several jobs) have surfaced that we can no longer count on their being a "support email/link" in any given app-details page (per #marketplace on IRC); see the test at:

https://github.com/mozilla/marketplace-tests/blob/master/tests/desktop/consumer_pages/test_details_page.py#L50

14:55:04 =================================== FAILURES ===================================
14:55:04 ______ TestDetailsPage.test_that_application_page_contains_proper_objects ______
14:55:04 [gw0] darwin -- Python 2.7.5 /Users/Shared/Jenkins/Home/jobs/marketplace.PROD/workspace/.env/bin/python
14:55:04 self = <tests.desktop.consumer_pages.test_details_page.TestDetailsPage instance at 0x10b015488>
14:55:04 mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x10b120c68>
14:55:04 
14:55:04     @pytest.mark.nondestructive
14:55:04     def test_that_application_page_contains_proper_objects(self, mozwebqa):
14:55:04     
14:55:04         home_page = Home(mozwebqa)
14:55:04         home_page.go_to_homepage()
14:55:04     
14:55:04         Assert.true(home_page.is_the_current_page)
14:55:04     
14:55:04         search_term = self._take_first_new_app_name(mozwebqa)
14:55:04         details_page = home_page.header.search_and_click_on_app(search_term)
14:55:04     
14:55:04         Assert.true(details_page.is_the_current_page)
14:55:04     
14:55:04         Assert.equal(details_page.app_name, search_term)
14:55:04     
14:55:04         # Check the application icon
14:55:04         Assert.true(details_page.is_image_visible)
14:55:04     
14:55:04         # Check application title
14:55:04         Assert.equal(details_page.name, details_page.app_name)
14:55:04     
14:55:04         # Check Application Developer username
14:55:04         Assert.true(details_page.is_app_dev_username_visible)
14:55:04     
14:55:04         # Check the install/purchase button
14:55:04         Assert.true(details_page.is_install_button_visible)
14:55:04     
14:55:04         # Check the application description
14:55:04         Assert.true(details_page.is_application_description_visible)
14:55:04     
14:55:04         # Check the image preview section of the application
14:55:04         Assert.true(details_page.is_image_preview_section_visible)
14:55:04     
14:55:04         # Check if the support email link is visible
14:55:04 >       Assert.true(details_page.is_support_email_visible)
14:55:04 
14:55:04 tests/desktop/consumer_pages/test_details_page.py:51: 
14:55:04 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
14:55:04 
14:55:04 self = <class 'unittestzero.Assert'>, first = False, msg = None
14:55:04 
14:55:04     @classmethod
14:55:04     def true(self, first, msg=None):
14:55:04         """
14:55:04             Asserts that what is given is equal to True
14:55:04     
14:55:04             :Args:
14:55:04              - First object to be tested
14:55:04              - Message that will be printed if it fails
14:55:04             """
14:55:04     
14:55:04 >       assert bool(first) is True, msg
14:55:04 E       AssertionError: None
14:55:04 
14:55:04 .env/lib/python2.7/site-packages/unittestzero.py:79: AssertionError
14:55:04 ------------------------------- pytest-mozwebqa --------------------------------
14:55:04 Failing URL: https://marketplace.firefox.com/app/saldo-bus-metro-panama?src=search

**Comment by AndreiH** [comment]
so that Assert needs to be removed, did you talked to the devs on #marketplace and they are ok with it?

**Comment by AndreiH** [comment]
This issue was addressed. Thanks!
