### ISSUE TITLE
Add test for the Free button under apps on Homepage not triggering an install

### ISSUE THREAD

**Issue by AndreiH** [mozilla/marketplace-tests#605]
The Free button under each app on Home Page when clicked triggers an install of that app.
That shouldn't be happening. There's already a bug on that and we have to add a test that nothing happens on clicking that text.

**Comment by AndreiH** [comment]
I worked on this today and this is kinda confusing.
There are 4 types of buttons on Home Page (see screenshot) . They are all clickable.
I think that the ones that are non-bordered are the ones to be tested if they trigger an app install when clicked. Is that right @krupa ? 
So, I was thinking that we could check this by Asserting if those specific "Free" buttons are clickable or not. If they are clickable there's a bug.

![2](https://cloud.githubusercontent.com/assets/2787766/5860776/84dc3d12-a26c-11e4-9d32-960e320f03ab.png)

Also, can you give me a bug number @krupa? I wasn't successful in finding one.

**Comment by krupa** [comment]
This feature has been removed with a UX redesign.
