### ISSUE TITLE
Add a test to complete an app purchase an Desktop

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#606]
Desktop support for payments just landed. Let us add a test to buy an app on desktop.

**Comment by AndreiH** [comment]
Thanks @krupa . I will work on this, but first we have to merge  https://github.com/mozilla/marketplace-tests/pull/584 PR for creating a new user

**Comment by bobsilverberg** [comment]
This was completed in https://github.com/mozilla/marketplace-tests/commit/5bf45e0181c579141e08eb8ed6d6799b61b8f713
