### ISSUE TITLE
Test adding a screenshot on Dev_hub fails because send_keys() method

### ISSUE THREAD

**Issue by AndreiH** [mozilla/marketplace-tests#618]
<code>send_keys</code> method does not inserts the screenshot anymore in the input field.
The method passes but nothing happens. I looked over this but I cannot find the issue.
Locators are ok, path is ok, method passes and manually it cannot be reproduced.

Please see : http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.DEV.developer_hub.saucelabs/1760/HTML_Report/

**Comment by AndreiH** [comment]
I just tried adding the workaround that @bobsilverberg used in PR: https://github.com/mozilla/marketplace-tests/pull/621
Modified this: https://github.com/mozilla/marketplace-tests/blob/master/pages/desktop/developer_hub/edit_app.py#L265
to 
<code>ActionChains(self.selenium).send_keys_to_element(element, value).perform()</code>
or 
<code>ActionChains(self.selenium).move_to_element(element).send_keys(value).perform()</code>
and it has no effect. :(

**Comment by bobsilverberg** [comment]
@krupa @davehunt I have tried a few things today and cannot get this to work either. I'm not sure if something changed in the page, or if it is a Selenium issue, although I suspect these tests used to pass with the current Selenium version. @krupa can you look into whether something has changed with the page and the code for uploading screenshots? @davehunt do you have any other suggestions?

**Comment by davehunt** [comment]
I'm assuming this isn't a Sauce Labs issue? Have you tried with the latest versions of Selenium and Firefox? It sounds like it might be a Selenium bug - it might also be worth trying with Marionette to see if it works there.

**Comment by bobsilverberg** [comment]
This has been fixed.
