### ISSUE TITLE
Add a test make an app purchase on Android

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#620]
Android Payments are going to be a thing soon and we should have test coverage for it anyways.

Currently, there is a blocking bug https://bugzilla.mozilla.org/show_bug.cgi?id=1130057 but older versions of the nightly should be okay.

**Comment by AndreiH** [comment]
I explained this before in a mail that I sent. We cannot do Payments on an Emulator that is running on Saucelabs. The response that they gave us for this is to wait until they have real devices placed.

**Comment by krupa** [comment]
## Pre-conditions:
a. Tester has https://addons.mozilla.org/en-US/firefox/addon/dev-marketplace/
b.  Tester has Firefox 38 installed on their Android device.

## Steps to reproduce:
1. Open https://marketplace-dev.allizom.org on your fennec browser.
2. Search for 'Test Zippy With me' app or any of the paid apps on dev.
3. Click the purchase button for one of the listed paid apps
4. Sign in using firefox account
5. Enter PIN
6. Confirm purchase using Zippy.

**Comment by krupa** [comment]
Note that the screencast doesn't include steps to sign in (makes the video too long)
screencast: http://cl.ly/3c3r3E0L2y06

**Comment by davehunt** [comment]
Thanks @krupa so what's not shown in this screencast is the installation of the "Dev Marketplace" addon, but if we can achieve what that addon does without needing to install it that would be preferred.

The very last part of this video looks like an Android OS level prompt - can you confirm that? If that's the case I don't expect Marionette would help here, so we may need to be able to hand off to Appium or something else to complete the test.

/cc @AutomatedTester @ncalexan

**Comment by ncalexan** [comment]
Thanks @krupa!

On Thu, Jun 11, 2015 at 1:40 AM, Dave Hunt <notifications@github.com> wrote:

> Thanks @krupa <https://github.com/krupa> so what's not shown in this
> screencast is the installation of the "Dev Marketplace" addon, but if we
> can achieve what that addon does without needing to install it that would
> be preferred.
>
The add-on is simple, so we wouldn't necessarily need to configure this
using the add-on.


> The very last part of this video looks like an Android OS level prompt -
> can you confirm that? If that's the case I don't expect Marionette would
> help here, so we may need to be able to hand off to Appium or something
> else to complete the test.
>

It is definitely an Android OS level prompt.  I think we would want to
observe (and abort) the browser message that launches the installation
process on Android rather than try to interact with that prompt.

Seeing this flow, what I am most worried about is needing network level
access to dev-marketplace.allizom.org or whatever.  That more or less rules
out running /anything/ in TBPL/Tree Herder.

**Comment by davehunt** [comment]
> Seeing this flow, what I am most worried about is needing network level access to dev-marketplace.allizom.org or whatever. That more or less rules out running /anything/ in TBPL/Tree Herder.

It's likely that this particular test will not run on buildbot. Web QA runs end-to-end integration tests against deployed environments in Jenkins.

**Comment by ncalexan** [comment]
On Fri, Jun 12, 2015 at 1:57 AM, Dave Hunt <notifications@github.com> wrote:

> Seeing this flow, what I am most worried about is needing network level
> access to dev-marketplace.allizom.org or whatever. That more or less
> rules out running /anything/ in TBPL/Tree Herder.
>
> It's likely that this particular test will not run on buildbot. Web QA
> runs end-to-end integration tests against deployed environments in Jenkins.
>
Then you may be able to arrange this with an add-on that runs the test.
You would be able to drive the chrome (where necessary) and the content
using the add-on SDKs.

@erikvold did a bunch of work making testing with mobile add-ons on Travis
possible, see: https://github.com/erikvold/jpm-mobile and
https://github.com/erikvold/jpm-mobile-travis-example.  (For the record,
jpm-mobile was broken for me when I tried it a month ago, but it did not
appear serious.)

**Comment by krupa** [comment]
This has been de-prioritized.
