### ISSUE TITLE
Investigate/fix test_that_reports_abuse_as_anonymous_user and test_that_reports_abuse_as_signed_in_user

### ISSUE THREAD

**Issue by stephendonner** [mozilla/marketplace-tests#629]
See https://webqa-ci.mozilla.com/job/marketplace.dev.saucelabs/41/testReport/

We need to investigate and fix/file a bug on (if necessary):

test_that_reports_abuse_as_anonymous_user and test_that_reports_abuse_as_signed_in_user

Here's a sample stack:

__________ TestDetailsPage.test_that_reports_abuse_as_anonymous_user ___________
[gw12] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/marketplace.dev.saucelabs/workspace/.env/bin/python2.7
tests/desktop/consumer_pages/test_details_page.py:73: in test_that_reports_abuse_as_anonymous_user
>       report_abuse_box = details_page.click_report_abuse_button()
pages/desktop/consumer_pages/details.py:159: in click_report_abuse_button
>       return self.report_abuse_box
pages/desktop/consumer_pages/details.py:163: in report_abuse_box
>       report_abuse_box = self.find_element(*self._report_abuse_box_locator)
pages/page.py:138: in find_element
>       return self._selenium_root.find_element(*locator)
.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:664: in find_element
>                            {'using': by, 'value': value})['value']
.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:175: in execute
>           self.error_handler.check_response(response)
.env/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:166: in check_response
>       raise exception_class(message, screen, stacktrace)
E       NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":".abuse-form"}
E       For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
E       Build info: version: '2.43.0', revision: '597b76b', time: '2014-09-09 20:52:14'
E       System info: host: 'WIN-R1JBAO1CNPS', ip: '172.20.43.136', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_60'
E       Driver info: driver.version: unknown
E       Stacktrace:
E           at <anonymous class>.FirefoxDriver.prototype.findElementInternal_ (file:///C:/Users/ADMINI~1/AppData/Local/Temp/anonymous2246217391458652185webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9618:26)
E           at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify (file:///C:/Users/ADMINI~1/AppData/Local/Temp/anonymous2246217391458652185webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:548:5)
------------------------------- pytest-mozwebqa --------------------------------
Failing URL: https://marketplace-dev.allizom.org/app/connecta2?src=search
__________ TestDetailsPage.test_that_reports_abuse_as_signed_in_user ___________
[gw5] linux2 -- Python 2.7.9 /var/lib/jenkins/jobs/marketplace.dev.saucelabs/workspace/.env/bin/python2.7
tests/desktop/consumer_pages/test_details_page.py:103: in test_that_reports_abuse_as_signed_in_user
>       report_abuse_box = details_page.click_report_abuse_button()
pages/desktop/consumer_pages/details.py:159: in click_report_abuse_button
>       return self.report_abuse_box
pages/desktop/consumer_pages/details.py:163: in report_abuse_box
>       report_abuse_box = self.find_element(*self._report_abuse_box_locator)
pages/page.py:138: in find_element
>       return self._selenium_root.find_element(*locator)
.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:664: in find_element
>                            {'using': by, 'value': value})['value']
.env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:175: in execute
>           self.error_handler.check_response(response)
.env/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:166: in check_response
>       raise exception_class(message, screen, stacktrace)
E       NoSuchElementException: Message: Unable to locate element: {"method":"css selector","selector":".abuse-form"}
E       For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
E       Build info: version: '2.43.0', revision: '597b76b', time: '2014-09-09 20:52:14'
E       System info: host: 'WIN-R1JBAO1CNPS', ip: '172.20.32.246', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_60'
E       Driver info: driver.version: unknown
E       Stacktrace:
E           at <anonymous class>.FirefoxDriver.prototype.findElementInternal_ (file:///C:/Users/ADMINI~1/AppData/Local/Temp/anonymous5865143883335590959webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:9618:26)
E           at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify (file:///C:/Users/ADMINI~1/AppData/Local/Temp/anonymous5865143883335590959webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:548:5)
------------------------------- pytest-mozwebqa --------------------------------
Failing URL: https://marketplace-dev.allizom.org/app/connecta2?src=search
------------------------------- Captured stdout --------------------------------
fxapom created an account for email: eqtakverakrk@restmail.net at https://stable.dev.lcip.org/auth/ on 2015-03-11 16:43:18.371651

**Comment by mstriemer** [comment]
Looks like this is https://bugzilla.mozilla.org/show_bug.cgi?id=1139364

**Comment by stephendonner** [comment]
Indeed; which landed in https://github.com/mozilla/fireplace/pull/1070 and fixed us:

https://webqa-ci.mozilla.com/view/Marketplace/job/marketplace.dev.saucelabs/43/testReport/
