### ISSUE TITLE
Add a test to make an app purchase with region=India

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#632]
## Environment
Desktop

## Pre-condition
Tester is logged in

## Steps to reproduce
1.  Load marketplace on Firefox browser
2. Go to /debug and set region to India
3. Search for :paid on marketplace
4. Click the buy button for one of the apps in the search results

## Expected behavior
Enter PIN screen loads in a popup

**Comment by kumar303** [comment]
for context, this was always broken https://bugzilla.mozilla.org/show_bug.cgi?id=1143119 so we want to avoid regressions

**Comment by stephendonner** [comment]
@clouserw can we take this opportunity for someone from your team to work with us on adding this test?

**Comment by clouserw** [comment]
If you file a bug, we (ddurst) can add it to the KTLO tracker.

**Comment by krupa** [comment]
This has been de-priortized.
