### ISSUE TITLE
Investigate marketplace prod timeout issue for test_home_page

### ISSUE THREAD

**Issue by rbillings** [mozilla/marketplace-tests#638]
This test is repeatedly failing with a timeout error:
tests.desktop.consumer_pages.test_home_page.TestConsumerPage

4/1 https://webqa-ci.mozilla.com/job/marketplace.prod/115/HTML_Report/
4/2 https://webqa-ci.mozilla.com/job/marketplace.prod/124/HTML_Report/
4/6 https://webqa-ci.mozilla.com/job/marketplace.prod/132/HTML_Report/

**Comment by bobsilverberg** [comment]
I will take a look at this.

**Comment by bobsilverberg** [comment]
The specific test that is failing is `test_opening_every_category_page_from_categories_menu`. @rbillings it's good to add the test name to the issue as well.

**Comment by bobsilverberg** [comment]
PR #639 has been merged, and the test is passing now. Let's leave this open for a week or so to ensure that the test doesn't have future intermittents.

**Comment by bobsilverberg** [comment]
This test has passed consistently since the PR was merged. I am going to close this.
