### ISSUE TITLE
test_hosted_paid_app_submission is failing because there are no payment accounts set up

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests#640]
Failure can be seen at [1], but is fairly mysterious because of `try/except`. I believe that creating the appropriate payment account(s) in dev should fix the problem.

The user is mozilla.mp@gmail.com

@krupa can you fix this?

**Comment by stephendonner** [comment]
cc @jasonthomas too ^^^

**Comment by krupa** [comment]
This is now fixed.

**Comment by bobsilverberg** [comment]
@krupa This seems to be an issue again, I guess because of another recent db refresh. Can you please fix again?

**Comment by krupa** [comment]
done.
