### ISSUE TITLE
Add a test to install an app on desktop

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#657]
## Steps to reproduce:
1. Load marketplace(dev/stage)
2. Search for :desktop  
3. Install any of the apps listed in the search results

## Expected behavior
App is installed successfully.

**Comment by bobsilverberg** [comment]
Thanks @krupa. Do we need a separate test for this, or are we going to just install an app as an initial step for `test_settings_dropdown_menu`? I thought we had discussed the latter.

**Comment by krupa** [comment]
This is hard to add since it involves interaction with the Chrome. Since desktop is a low priority, we don't have the bandwidth to write and maintain this test,
