### ISSUE TITLE
Add a setup.cfg file to configure the behaviour of flake8

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests#667]
This is a simple task: 

1. Add a new file to the repo called `setup.cfg`. The file should look just like the file found at https://github.com/mozilla/mcom-tests/blob/master/setup.cfg
2. Update the `.travis.yml` file so the `script:` line reads:
```yml
script: "flake8 ."
```

**Comment by rbillings** [comment]
This was done and merged
