### ISSUE TITLE
Update paid app submission test to add a payment account

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#674]
https://github.com/mozilla/marketplace-tests/blob/master/tests/desktop/developer_hub/test_developer_hub_submit_apps.py needs to be updated to include adding a payment account IF it doesn't exist.

So, after submission, while the test is setting up payment details, it should check if an associated payment account exists. If not,

1. Navigate to the Compatibility & Payments page in the devhub
2. Click on the 'Add, manage or view transactions for your payment accounts' link
3. Click on 'Add a reference implementation account' button the lightbox.
4. Add Account Name, Name and Email fields.
5. Save changes
6. Select the newly added payment account from the dropdownbox.

## Expected behavior:
Payments is successfully set up for the test app.

**Comment by bobsilverberg** [comment]
I have started working on this. I hope to have a PR ready by Monday.

**Comment by davehunt** [comment]
Is this to resolve an intermittent failure or to test an additional user flow? If the former then I think I understand the need, however if it's the latter then I think we'd be giving a false positive every time this test ran whenever a payment account already exists.

**Comment by bobsilverberg** [comment]
The former. There is no intent to test the flow of adding a payment account.

**Comment by davehunt** [comment]
Okay, under what circumstances would there be no payment account?

**Comment by bobsilverberg** [comment]
When a db refresh has been done on dev.

**Comment by davehunt** [comment]
Okay, and I'm guessing there's no way to do this via an API? I'm also assuming we don't want to log anything when we have to create an account?
