### ISSUE TITLE
Review saucelabs failures on https://webqa-ci.mozilla.com/job/marketplace.dev.mobile.saucelabs/

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#675]
https://webqa-ci.mozilla.com/job/marketplace.dev.mobile.saucelabs/ has a lot of failures with TimeoutException. It isn't clear from the saucelabs screencasts, what is tripping up the tests but the behavior is expected and these tests should be passing.

**Comment by davehunt** [comment]
They're waiting for at least one result to be displayed. We're using CSS selector `.product .info` to find results ([code](https://github.com/mozilla/marketplace-tests/blob/4f6c4c082377d8f39c1aeeee3dab894db9ba69bf/pages/mobile/search.py#L16)). I can confirm on Marketplace dev that this locator returns nothing.

**Comment by davehunt** [comment]
On prod the locator is still working, so I'm guessing we need to update the locator for dev and staging.

**Comment by davehunt** [comment]
Looks like it comes from https://github.com/mozilla/fireplace/commit/b6890ff5d20de95185cd3bb5ac6f2023fb28f295, which dropped 'product' from the class of the link.
