### ISSUE TITLE
Add a test to open a website from the details page

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#689]
## Steps to reproduce:
1. Open marketplace-dev app on your firefoxOS device
2. Go to New tab
3. Filter the content to show only Websites
4. Click on one of the listed websites to load the details page
5.  Click "Open"

## Expected behavior:
The website loads in a new tab on the browser

**Comment by bobsilverberg** [comment]
This was opened in the wrong repo. I opened https://github.com/mozilla/marketplace-tests-gaia/issues/121 to replace this.
