### ISSUE TITLE
Review and improve waits in the developer hub tests

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests#693]
A lot of the tests seem to have negative waits that are taking a long time (e.g., wait for element to not be present/visible that needs to time out in order to return). We should review these and fix the waits as we could significantly speed up the test suite.

**Comment by bobsilverberg** [comment]
This task will be expanded to review and potentially change the waits for the whole suite, not just developer hub. The plan for this is:
1. Disable implicit waits in Selenium
2. Review tests that are broken as a result of #1, above
3. Determine a strategy for waits for the suite, which could include creating our own custom ExpectedConditions class.

**Comment by stephendonner** [comment]
Closing per https://github.com/mozilla/marketplace-tests/issues/760
