### ISSUE TITLE
Conduct a quality audit of the tests in this repo

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests#698]
Some members of the team have noticed problems with some of the tests in this repo. They don't seem to be properly testing what they are intended to test.

This task is to review all tests in the repo to ensure that they are accurate. This will also include a review of whether the tests are still needed or not.

**Comment by stephendonner** [comment]
Closing due to https://github.com/mozilla/marketplace-tests/issues/760
