### ISSUE TITLE
Test to check for the Desktop Games homepage

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#706]
## Description
The desktop marketplace homepage will now only show games.

## Steps to test
1. Load marketplace-dev on your desktop Firefox.
1. Check for the following -
  1. There is PLAY GREAT DESKTOP GAMES header. Underneath it, we show information regarding the Game's name, developer and category.
  1. There is a primary featured game block with a button to play the game
  1. There are three secondary featured games. On hover, each section shows the category type, game icon, game name, game developer and the button to play the game 
  1. There is a link 'FIND MORE GREAT GAMES'

**Comment by GroteGnoom** [comment]
On a manual test of step iii, no game developer is visible on hover. Is this a bug?

**Comment by krupa** [comment]
I think we should hold off on this test since there is talk of reverting the Games-related changes we did to Desktop.

**Comment by krupa** [comment]
This will be reverted soon.
