### ISSUE TITLE
Test to check for the Games category page

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#707]
## Steps to test
1. Load marketplace-dev app on your desktop Firefox
1. Click on the Find more great games link
1. Check for the following
  1. There is a PLAY GREAT DESKTOP GAMES header
  1. There is a banner explaining why HTML5 games are great
  1. On hover on one of the category-featured games, we show the category, icon, name, developer and the button
  1. There are filters which can be applied to the listed games. By default, 'All Games' is selected.

**Comment by GroteGnoom** [comment]
3. iii. Does not seem to work on a manual test:
When I go to https://marketplace-dev.allizom.org/games/all and hover over one of the shown games, this is the result:
![gamepiconhover](https://cloud.githubusercontent.com/assets/8137208/10411805/40ae8590-6f72-11e5-8472-25d3e58a3bb2.png)
So the category, icon, name and 'Play now' button are visible, but I don't see a developer.

Is the test correct? Am I interpreting "category-featured games" wrong? If so, where are they?

**Comment by krupa** [comment]
Let us hold off on this test.

**Comment by krupa** [comment]
This will be reverted soon
