### ISSUE TITLE
Inspect the timeouts on marketplace-dev builds

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#720]
https://webqa-ci.mozilla.com/job/marketplace.dev/386/testReport/ has failures related to timeouts. We need to review why those timeouts are happening.

**Comment by davehunt** [comment]
I just reran the suite and everything passed. The timeout looks like a failure of the Selenium server to respond so it may have been network issues between our Jenkins box and the VM running the test. I'm not sure what else we can do to investigate this particular issue at this time. Please reopen if you see it again.
