### ISSUE TITLE
Upcoming Nav changes will break all marketplace tests for Consumer pages; need to update tests

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#725]
There is a Nav change which will change the entire layout of marketplace mobile experience. It is still not landed but when it does, almost all our tests are going to break. This is just a proactive issue to fix those tests when the PR lands.

**Comment by davehunt** [comment]
Is there any chance the Marketplace devs can help us with the test failures? They should see the failures in their Travis results. Do you have a link to the PR with the pending changes?

**Comment by bobsilverberg** [comment]
I didn't see a response from @krupa on this. Looking at https://github.com/mozilla/fireplace, I am guessing the commit is https://github.com/mozilla/fireplace/commit/1f661f87c54f174c4cb49c80c73777917f4bc00d#diff-d8e033f39f0b267cfa721273c38aa92b. I am going to start work on updating the page objects to deal with these code changes.

**Comment by bobsilverberg** [comment]
I found a bug [1] while testing this, so I am holding off on making any changes, for now, in the hopes that that bug gets fixed.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1218812

**Comment by bobsilverberg** [comment]
This has been discussed in #marketplace and with @krupa and the suggestion is to just ignore the test results for marketplace-dev for the rest of the week as work is ongoing on this.

**Comment by bobsilverberg** [comment]
FTR, I am working on this again.
