### ISSUE TITLE
Investigate/fix test_opening_category_pages_from_categories_menu

### ISSUE THREAD

**Issue by stephendonner** [mozilla/marketplace-tests#726]
test_opening_category_pages_from_categories_menu has been really problematic (at least on dev):

https://webqa-ci.mozilla.com/job/marketplace.dev.sanity.saucelabs/1049/testReport/junit/test_home_page/TestConsumerPage/test_opening_category_pages_from_categories_menu/history/

Let's try to figure out if this is a test-automation code/wait problem, a slow dev-server problem, and/or both, and do something about it.

**Comment by davehunt** [comment]
I've seen this too, and I supect the wait for the element to not be moving has a bug. This was previously failing much more frequently before the new wait, but obviously we're far from stable. I suspect some debug information in the expected condition might provide some light. I can look into this soon.

**Comment by davehunt** [comment]
Please reopen if this is still an issue.
