### ISSUE TITLE
Test add-on submission

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#735]
NOTE: The test account needs to be given access to on both dev and stage

## steps to reproduce:
1. Using an account with access, sign into https://marketplace-dev.allizom.org/content/
2. Click on 'Submit a FirefoxOS Add-on'
3. Upload a valid add-on file
4. Submit

## Expected behavior:
Add-on submission is successful

**Comment by bobsilverberg** [comment]
Thanks @krupa. Are you able to set up those accounts and provide me with the credentials? Are you able to provide me with a valid add-on file?

**Comment by krupa** [comment]
Can we just use the current credentials? I can just give that account access. yes, I can provide you with a test file. Since github doesn't allow uploading .zip files, I will send it via email.

**Comment by bobsilverberg** [comment]
I am working on this now

**Comment by bobsilverberg** [comment]
I guess the commit message needs to say `Fixes #735` rather than `Fixes Issue #735` as this issue does not seem to have auto-closed. In any case, this was fixed in https://github.com/mozilla/marketplace-tests/commit/8daa3115e2519a3d454f681328cb05479fbc0d6b

**Comment by davehunt** [comment]
:balloon: :tada: :balloon: :tada: :balloon:

**Comment by bobsilverberg** [comment]
:)
