### ISSUE TITLE
xfail the paid app submission test

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#741]
Until Zippy is back up again, this test will fail. Our Ops person is on PTO and we are heading into the Holidays. We should xfail it.

test_developer_hub_submit_apps.TestDeveloperHubSubmitApps.test_hosted_paid_app_submission is the one we need to xfail.

**Comment by davehunt** [comment]
I'm not exactly sure what Zippy is, but I see that this test is failing. Is there a bug on file for getting this fixed? I'm not keen on xfailing tests without more information, but I will have a pull request open shortly.
