### ISSUE TITLE
Retire all android related tests for Marketplace

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#750]
We will soon stop supporting webapps on Android. Let us retire all tests related to Android and stop the testsuites which are running in Saucelabs.

**Comment by davehunt** [comment]
@krupa to clarify, do you mean that all files under `marketplace-tests/tests/mobile/` and `marketplace-tests/pages/mobile/` can now be removed?

**Comment by davehunt** [comment]
Pull request #755 submitted for review.

**Comment by davehunt** [comment]
Fixed in https://github.com/mozilla/marketplace-tests/pull/755
