### ISSUE TITLE
Retire all tests related to payments on Marketplace

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#751]
We have a few payments tested which have been xfailed for a while. Let us retire them. Thanks!

**Comment by davehunt** [comment]
It looks like #748 is a duplicate of this. As this covers multiple tests though, let's keep this one open.

**Comment by davehunt** [comment]
@krupa I can only find [one test](https://github.com/mozilla/marketplace-tests/blob/4cc0037d6ddafc8d2e8c36e04f76d782d7f0f44f/tests/desktop/consumer_pages/test_purchase_app.py) are you aware of any others?

**Comment by davehunt** [comment]
Pull request #755 submitted for review.

**Comment by davehunt** [comment]
Fixed in https://github.com/mozilla/marketplace-tests/pull/755
