### ISSUE TITLE
Update devhub tests to accommodate switching to the new IARC api

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#752]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1143040, we updated Content ratings to point to their latest API. This changed the UI for content ratings and thus all our devhub tests are failing. 

We need to update our tests.

**Comment by davehunt** [comment]
@krupa or @clouserw could you provide some documentation on the new version of the API, which might help us to update the tests?

**Comment by stephendonner** [comment]
Perhaps @diox from https://github.com/mozilla/zamboni/pull/3489 can help us here, too?

**Comment by diox** [comment]
What do you need help with exactly ?

Quick summary of the changes:
- If you go through IARC questionnaire, the flow is the same. But I guess you don't.
- If you want to skip that, instead of knowing a submission id + security code you need to know a valid IARC certificate id. Our API to set content ratings has changed as a result, it now uses a single `cert_id` parameter. The [documentation was updated](http://firefox-marketplace-api.readthedocs.org/en/latest/topics/app_submission.html#id3) (I was lazy and updated the docs even though the change is waffle off everywhere except dev, I assumed nobody really cared except us).

**Comment by davehunt** [comment]
@diox In that case I believe we may need an update and new release of [Marketplace.Python](https://github.com/mozilla/Marketplace.Python). It's currently failing on [this line](https://github.com/mozilla/Marketplace.Python/blob/master/marketplace/client.py#L234) against dev.

**Comment by diox** [comment]
The owner of the test application on dev (and stage later when we enable IARC on stage, if those tests also run there) will need to follow the new IARC questionnaire on dev from the test app and get an IARC certificate ID. Once this is done it will need to be copied in [mock_application.py](https://github.com/mozilla/marketplace-tests/blob/master/mocks/mock_application.py#L42) we can implement the required API changes (which are fairly trivial).

Also, I hope IARC lets you re-use the same cert... I'm actually surprised it's working at the moment with the same submission id and security code re-used every time the tests run...

**Comment by davehunt** [comment]
I'm not sure what you mean by the 'owner of the test application'. These tests generate a new application for each test, so there is no single test application.

**Comment by diox** [comment]
I should have added a plural :) My point was, it's probably better to start from one of the test applications in order to generate the certificate properly.

**Comment by davehunt** [comment]
Okay thanks, I'm not familiar enough with Marketplace or these tests to know where to find the IARC questionnaire on dev or how to complete it if I did. Perhaps @krupa can help here?

**Comment by diox** [comment]
I just pushed something to show the certificate ID in the content ratings page for each app in devhub, it will land on dev shortly and make our lives easier.

**Comment by davehunt** [comment]
@krupa we've stopped running these tests in CI, so can we close this issue?

**Comment by krupa** [comment]
yes, let us close this issue.
