### ISSUE TITLE
Retire tests/builds/repos related to Marketplace

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests#760]
Let us remove the tests/builds/repos related to Marketplace
## builds:
marketplace.dev
marketplace.dev.developer_hub
marketplace.dev.developer_hub.saucelabs
marketplace.dev.sanity.saucelabs
marketplace.dev.saucelab
marketplace.mozilla-b2g32_v2_0.nightly
marketplace.prod
marketplace.prod.sanity.saucelabs
marketplace.prod.saucelabs
marketplace.stage.developer_hub.saucelabs
marketplace.stage.sanity.saucelabs
marketplace.stage.saucelabs

## repos:
https://github.com/mozilla/marketplace-tests
https://github.com/mozilla/marketplace-tests-gaia

**Comment by stephendonner** [comment]
Taking - I'll do the above, per https://wiki.mozilla.org/QA/Execution/Web_Testing/Repositories#Deactivating_a_repository
